import { useEffect,useState } from "react";
import { Loader2,Save,ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import type { AnalyticsSetting,Provider } from "@/lib/analytics/types";

const labels:Record<Provider,string>={meta:"Meta",ga4:"Google Analytics 4",google_ads:"Google Ads",tiktok:"TikTok"};
const patterns:Record<Provider,RegExp>={meta:/^[0-9]{5,30}$/,ga4:/^G-[A-Z0-9]{4,20}$/,google_ads:/^AW-[0-9]{5,20}$/,tiktok:/^[A-Z0-9]{10,30}$/};
export default function AnalyticsSettingsView(){const [rows,setRows]=useState<AnalyticsSetting[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState<Provider|null>(null);
  useEffect(()=>{void (async()=>{const {data,error}=await (supabase as any).from("analytics_settings").select("provider,enabled,public_id,conversion_id,conversion_label").order("provider");if(error)toast.error(error.message);else setRows(data??[]);setLoading(false)})()},[]);
  const patch=(p:Provider,v:Partial<AnalyticsSetting>)=>setRows(r=>r.map(x=>x.provider===p?{...x,...v}:x));
  const save=async(row:AnalyticsSetting)=>{const id=row.provider==="google_ads"?row.conversion_id:row.public_id;if(row.enabled&&(!id||!patterns[row.provider].test(id)||(row.provider==="google_ads"&&!/^[A-Za-z0-9_-]{1,100}$/.test(row.conversion_label??""))))return toast.error(`Formato inválido para ${labels[row.provider]}`);setSaving(row.provider);const {error}=await (supabase as any).from("analytics_settings").update({enabled:row.enabled,public_id:row.provider==="google_ads"?null:row.public_id||null,conversion_id:row.provider==="google_ads"?row.conversion_id||null:null,conversion_label:row.provider==="google_ads"?row.conversion_label||null:null}).eq("provider",row.provider);setSaving(null);if(error)toast.error(error.message);else toast.success("Configuración guardada")};
  if(loading)return <Loader2 className="h-6 w-6 animate-spin text-neon-blue"/>;return <div className="space-y-5"><div><h2 className="font-display text-2xl font-bold">Píxeles y seguimiento</h2><p className="text-sm text-muted-foreground">Solo identificadores públicos. Los scripts se cargan después del consentimiento correspondiente.</p></div>{rows.map(row=><section key={row.provider} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">{labels[row.provider]}</h3><p className="text-xs text-muted-foreground">{row.enabled&&((row.public_id||row.conversion_id))?"Configurado y activado":"No activo"}</p></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={row.enabled} onChange={e=>patch(row.provider,{enabled:e.target.checked})}/> Activado</label></div><div className="mt-4 grid gap-3 md:grid-cols-2">{row.provider!=="google_ads"?<Field label={row.provider==="ga4"?"Measurement ID":`${labels[row.provider]} Pixel ID`} value={row.public_id??""} onChange={v=>patch(row.provider,{public_id:v.toUpperCase().trim()})}/>:<><Field label="Conversion ID" value={row.conversion_id??""} onChange={v=>patch(row.provider,{conversion_id:v.toUpperCase().trim()})}/><Field label="Conversion Label" value={row.conversion_label??""} onChange={v=>patch(row.provider,{conversion_label:v.trim()})}/></>}</div><button onClick={()=>save(row)} disabled={saving===row.provider} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-neon-blue px-4 py-2 text-sm font-semibold text-black disabled:opacity-50">{saving===row.provider?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>} Guardar</button></section>)}<div className="flex gap-2 rounded-xl border border-neon-green/30 bg-neon-green/5 p-4 text-sm"><ShieldCheck className="h-5 w-5 text-neon-green"/>No se guardan tokens ni secretos de APIs publicitarias.</div></div>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-xs uppercase tracking-wide text-muted-foreground">{label}<input value={value} onChange={e=>onChange(e.target.value)} maxLength={100} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm normal-case text-foreground"/></label>}
