/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CambiosYDevolucionesRouteImport } from './routes/cambios-y-devoluciones'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CrearMiPackRouteImport } from './routes/crear-mi-pack'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PersonalizadorRouteImport } from './routes/personalizador'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as ApiPublicHooksCleanupRouteImport } from './routes/api/public/hooks/cleanup'
import { Route as ApiPublicHooksCspReportRouteImport } from './routes/api/public/hooks/csp-report'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as ApiPublicWebhooksShopifyRouteImport } from './routes/api/public/webhooks/shopify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiosYDevolucionesRoute = CambiosYDevolucionesRouteImport.update({
  id: '/cambios-y-devoluciones',
  path: '/cambios-y-devoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearMiPackRoute = CrearMiPackRouteImport.update({
  id: '/crear-mi-pack',
  path: '/crear-mi-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizadorRoute = PersonalizadorRouteImport.update({
  id: '/personalizador',
  path: '/personalizador',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const ApiPublicHooksCleanupRoute = ApiPublicHooksCleanupRouteImport.update({
  id: '/api/public/hooks/cleanup',
  path: '/api/public/hooks/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCspReportRoute = ApiPublicHooksCspReportRouteImport.update({
  id: '/api/public/hooks/csp-report',
  path: '/api/public/hooks/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksShopifyRoute =
  ApiPublicWebhooksShopifyRouteImport.update({
    id: '/api/public/webhooks/shopify',
    path: '/api/public/webhooks/shopify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cambios-y-devoluciones': typeof CambiosYDevolucionesRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/crear-mi-pack': typeof CrearMiPackRoute
  '/faq': typeof FaqRoute
  '/personalizador': typeof PersonalizadorRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/public/hooks/cleanup': typeof ApiPublicHooksCleanupRoute
  '/api/public/hooks/csp-report': typeof ApiPublicHooksCspReportRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/shopify': typeof ApiPublicWebhooksShopifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cambios-y-devoluciones': typeof CambiosYDevolucionesRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/crear-mi-pack': typeof CrearMiPackRoute
  '/faq': typeof FaqRoute
  '/personalizador': typeof PersonalizadorRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/public/hooks/cleanup': typeof ApiPublicHooksCleanupRoute
  '/api/public/hooks/csp-report': typeof ApiPublicHooksCspReportRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/shopify': typeof ApiPublicWebhooksShopifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cambios-y-devoluciones': typeof CambiosYDevolucionesRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/crear-mi-pack': typeof CrearMiPackRoute
  '/faq': typeof FaqRoute
  '/personalizador': typeof PersonalizadorRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/public/hooks/cleanup': typeof ApiPublicHooksCleanupRoute
  '/api/public/hooks/csp-report': typeof ApiPublicHooksCspReportRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/shopify': typeof ApiPublicWebhooksShopifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cambios-y-devoluciones'
    | '/catalogo'
    | '/contacto'
    | '/crear-mi-pack'
    | '/faq'
    | '/personalizador'
    | '/privacidad'
    | '/sitemap.xml'
    | '/terminos'
    | '/admin/orders'
    | '/pedido/$id'
    | '/admin/orders/$id'
    | '/api/public/hooks/cleanup'
    | '/api/public/hooks/csp-report'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/shopify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cambios-y-devoluciones'
    | '/catalogo'
    | '/contacto'
    | '/crear-mi-pack'
    | '/faq'
    | '/personalizador'
    | '/privacidad'
    | '/sitemap.xml'
    | '/terminos'
    | '/admin/orders'
    | '/pedido/$id'
    | '/admin/orders/$id'
    | '/api/public/hooks/cleanup'
    | '/api/public/hooks/csp-report'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/shopify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cambios-y-devoluciones'
    | '/catalogo'
    | '/contacto'
    | '/crear-mi-pack'
    | '/faq'
    | '/personalizador'
    | '/privacidad'
    | '/sitemap.xml'
    | '/terminos'
    | '/admin/orders'
    | '/pedido/$id'
    | '/admin/orders/$id'
    | '/api/public/hooks/cleanup'
    | '/api/public/hooks/csp-report'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/shopify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CambiosYDevolucionesRoute: typeof CambiosYDevolucionesRoute
  CatalogoRoute: typeof CatalogoRoute
  ContactoRoute: typeof ContactoRoute
  CrearMiPackRoute: typeof CrearMiPackRoute
  FaqRoute: typeof FaqRoute
  PersonalizadorRoute: typeof PersonalizadorRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminosRoute: typeof TerminosRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ApiPublicHooksCleanupRoute: typeof ApiPublicHooksCleanupRoute
  ApiPublicHooksCspReportRoute: typeof ApiPublicHooksCspReportRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  ApiPublicWebhooksShopifyRoute: typeof ApiPublicWebhooksShopifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambios-y-devoluciones': {
      id: '/cambios-y-devoluciones'
      path: '/cambios-y-devoluciones'
      fullPath: '/cambios-y-devoluciones'
      preLoaderRoute: typeof CambiosYDevolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-mi-pack': {
      id: '/crear-mi-pack'
      path: '/crear-mi-pack'
      fullPath: '/crear-mi-pack'
      preLoaderRoute: typeof CrearMiPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizador': {
      id: '/personalizador'
      path: '/personalizador'
      fullPath: '/personalizador'
      preLoaderRoute: typeof PersonalizadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/api/public/hooks/cleanup': {
      id: '/api/public/hooks/cleanup'
      path: '/api/public/hooks/cleanup'
      fullPath: '/api/public/hooks/cleanup'
      preLoaderRoute: typeof ApiPublicHooksCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/csp-report': {
      id: '/api/public/hooks/csp-report'
      path: '/api/public/hooks/csp-report'
      fullPath: '/api/public/hooks/csp-report'
      preLoaderRoute: typeof ApiPublicHooksCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/shopify': {
      id: '/api/public/webhooks/shopify'
      path: '/api/public/webhooks/shopify'
      fullPath: '/api/public/webhooks/shopify'
      preLoaderRoute: typeof ApiPublicWebhooksShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CambiosYDevolucionesRoute: CambiosYDevolucionesRoute,
  CatalogoRoute: CatalogoRoute,
  ContactoRoute: ContactoRoute,
  CrearMiPackRoute: CrearMiPackRoute,
  FaqRoute: FaqRoute,
  PersonalizadorRoute: PersonalizadorRoute,
  PrivacidadRoute: PrivacidadRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminosRoute: TerminosRoute,
  PedidoIdRoute: PedidoIdRoute,
  ApiPublicHooksCleanupRoute: ApiPublicHooksCleanupRoute,
  ApiPublicHooksCspReportRoute: ApiPublicHooksCspReportRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  ApiPublicWebhooksShopifyRoute: ApiPublicWebhooksShopifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
